### ISSUE TITLE
Blank lines aren't captured

### ISSUE THREAD

**Issue by gaddman** [rundeck-plugins/multiline-regex-datacapture-filter#3]
Blank lines in the middle of a matching regex are not captured by the multiline filter. When used with the _Hide Output_ option this leaves blank lines in the output.

**Sample job to reproduce:**
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6338f847-8f8f-44ee-9cd5-dd9e98f7e410
  loglevel: INFO
  name: blank output
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: echo -e "line1\nline2\n\n\n\n\n\n\n\n\nline3"
      description: create sample output with blank lines
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            hideOutput: 'true'
            logData: 'true'
            name: output
            regex: (.*)
          type: key-value-data-multilines
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: 6338f847-8f8f-44ee-9cd5-dd9e98f7e410
```

And sample output (in node view, but log view is much the same):
![image](https://user-images.githubusercontent.com/1311209/77988500-0330fa80-7379-11ea-8170-2bd912169024.png)

In my scenario I'd like the log to be empty unless I output some specific data, and I'm using the _Hide Output_ option to achieve this. But instead the log includes a number of blank lines for every node.

A workaround is to add a _Quiet Output_ log filter with an appropriate regex match.
